<?php
$event = $this->getEvent();
?>
<div class="page-main-actions">
    <div class="page-actions-placeholder"></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="Orders">
            <div class="page-actions-buttons">
                <button title="<?php echo __("Back") ?>" type="button" class="scalable default" onclick="location.href = '<?php echo $this->getListUrl() ?>';">
                    <span><?php echo __("Back") ?></span>
                </button>
                <?php if($prevEventUrl = $this->getPrevEventUrl()): ?>
                <button title="<?php echo __("Previous Event") ?>" type="button" class="scalable primary" onclick="location.href = '<?php echo $prevEventUrl ?>';">
                    <span><?php echo __("Previous Event") ?></span>
                </button>
                <?php endif; ?>
                <?php if($nextEventUrl = $this->getNextEventUrl()): ?>
                    <button title="<?php echo __("Next Event") ?>" type="button" class="scalable primary" onclick="location.href = '<?php echo $nextEventUrl ?>';">
                        <span><?php echo __("Next Event") ?></span>
                    </button>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<table class="admin__table-secondary">
    <tr>
        <th width="200"><strong><?php echo __('Event Id') ?></strong></th>
        <td><?php echo $event->getId() ?></td>
    </tr>
    <tr>
        <th><strong><?php echo __('Created Date') ?></strong></th>
        <td><?php echo __('%1 at %2', $this->formatDate($event->getCreatedAt()), $this->formatTime($event->getCreatedAt())) ?></td>
    </tr>
    <tr>
        <th><strong><?php echo __('Event Name') ?></strong></th>
        <td><?php echo $event->getEventName() ?: __('None') ?></td>
    </tr>
    <tr>
        <th><strong><?php echo __('Klarna Order Id') ?></strong></th>
        <td><?php echo $this->getKlarnaOrderId() ?: __('None') ?></td>
    </tr>
    <tr>
        <th><strong><?php echo __('Order Id') ?></strong></th>
        <td><?php echo $this->getOrderId() ?: __('None') ?></td>
    </tr>
    <tr>
        <th><strong><?php echo __('Message') ?></strong></th>
        <td><?php echo $this->getMessage() ?: __('None') ?></td>
    </tr>
    <?php if (!empty($event->getRawData())): ?>
        <tr>
            <th><strong><?php echo __('Event Raw Data') ?></strong></th>
            <td>
                <textarea style="width: 100%; height: 400px;"><?php echo $event->getRawData() ?></textarea>
            </td>
        </tr>
    <?php endif; ?>
</table>
